.PHONY: clean All

All:
	@echo "----------Building project:[ LinuxClient - Debug ]----------"
	@cd "LinuxClient" && "$(MAKE)" -f  "LinuxClient.mk"
clean:
	@echo "----------Cleaning project:[ LinuxClient - Debug ]----------"
	@cd "LinuxClient" && "$(MAKE)" -f  "LinuxClient.mk" clean
